### ISSUE TITLE
npm run start issue

### ISSUE THREAD

**Issue by johnnyontheweb** [xBimTeam/XbimWebUI#325]
#### Expected behavior:
Followed README.md, but it does not run. Npm and webpack installed, and "node_modules" populated.

#### Actual behavior or exception details:
```
npm run start

> @xbim/viewer@2.0.1 start C:\Users\devfolder\xBim\XbimWebUI
> npx concurrently "webpack serve --config webpack.dev.js --mode development" "webpack --watch --config webpack.worker.js "

[1] "serve" non ? riconosciuto come comando interno o esterno,
[1]  un programma eseguibile o un file batch.
[1] serve exited with code 1
[0] [webpack-cli] Compilation finished
[2] [webpack-cli] Compilation finished
[2] assets by status 0 bytes [cached] 1 asset
[2]
[2] ERROR in main
[2] Module not found: Error: Can't resolve './src' in 'C:\Users\devfolder\xBim\XbimWebUI'
[2] resolve './src' in 'C:\Users\devfolder\xBim\XbimWebUI'
[2]   using description file: C:\Users\devfolder\xBim\XbimWebUI\package.json (relative path: .)
[2]     Field 'browser' doesn't contain a valid alias configuration
[2]     using description file: C:\Users\devfolder\xBim\XbimWebUI\package.json (relative path: ./src)
[2]       no extension
[2]         Field 'browser' doesn't contain a valid alias configuration
[2]         C:\Users\devfolder\xBim\XbimWebUI\src is not a file
[2]       .js
[2]         Field 'browser' doesn't contain a valid alias configuration
[2]         C:\Users\devfolder\xBim\XbimWebUI\src.js doesn't exist
[2]       .json
[2]         Field 'browser' doesn't contain a valid alias configuration
[2]         C:\Users\devfolder\xBim\XbimWebUI\src.json doesn't exist
[2]       .wasm
[2]         Field 'browser' doesn't contain a valid alias configuration
[2]         C:\Users\devfolder\xBim\XbimWebUI\src.wasm doesn't exist
[2]       as directory
[2]         existing directory C:\Users\devfolder\xBim\XbimWebUI\src
[2]           using description file: C:\Users\devfolder\xBim\XbimWebUI\package.json (relative path: ./src)
[2]             using path: C:\Users\devfolder\xBim\XbimWebUI\src\index
[2]               using description file: C:\Users\devfolder\xBim\XbimWebUI\package.json (relative path: ./src/index)
[2]                 no extension
[2]                   Field 'browser' doesn't contain a valid alias configuration
[2]                   C:\Users\devfolder\xBim\XbimWebUI\src\index doesn't exist
[2]                 .js
[2]                   Field 'browser' doesn't contain a valid alias configuration
[2]                   C:\Users\devfolder\xBim\XbimWebUI\src\index.js doesn't exist
[2]                 .json
[2]                   Field 'browser' doesn't contain a valid alias configuration
[2]                   C:\Users\devfolder\xBim\XbimWebUI\src\index.json doesn't exist
[2]                 .wasm
[2]                   Field 'browser' doesn't contain a valid alias configuration
[2]                   C:\Users\devfolder\xBim\XbimWebUI\src\index.wasm doesn't exist
[2]
[2] webpack 5.24.2 compiled with 1 error in 312 ms
```

#### Version of the xBIM Viewer:
latest from this repo/master

**Comment by johnnyontheweb** [comment]
Just solved the error with serve command, that must be installed locally:
```
npm uninstall -g serve 
npm i -S serve
```

However, no way. I get the same error as above:
```
[2] assets by status 0 bytes [cached] 1 asset
[2]
[2] ERROR in main
[2] Module not found: Error: Can't resolve './src' in 'C:\Users\devfolder\xBim\XbimWebUI'
[2] resolve './src' in 'C:\Users\devfolder\xBim\XbimWebUI'
[2]   using description file: C:\Users\devfolder\xBim\XbimWebUI\package.json (relative path: .)
[2]     Field 'browser' doesn't contain a valid alias configuration
[2]     using description file: C:\Users\devfolder\xBim\XbimWebUI\package.json (relative path: ./src)
...
```

**Comment by martin1cerny** [comment]
Did you run `npm install` to restore all dependencies?

**Comment by johnnyontheweb** [comment]
I forgot, I just run it. Anyway, now the error I see in browser for `http://localhost:9001/dist/basic-viewer/index.html` is:
```
Html Webpack Plugin:
  Error: The loader "C:\Users\devfolder\xBim\XbimWebUI\node_modules\html-webpack-lugin\lib\loader.js!C:\Users\devfolder\xBim\XbimWebUI\examples\basic-viewer\index.html" didn't return html.
  
  - index.js:330 HtmlWebpackPlugin.evaluateCompilationResult
    [XbimWebUI]/[html-webpack-plugin]/index.js:330:24
  
  - index.js:237 
    [XbimWebUI]/[html-webpack-plugin]/index.js:237:22
  
  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5
  
  - async Promise.all
  
  - async Promise.all
```

**Comment by martin1cerny** [comment]
Just tried and all works fine. Make sure to
  1) Make sure you are not on an ancient version of node.js (I have node 12.14.1)
  2) Make sure you are not on an ancient version of npm (I have npm 6.14.11)
  3) Clone fresh copy of the repository
  4) `npm install`
  5) `npm run start`

**Comment by johnnyontheweb** [comment]
Thanks for the reply.
I have npm 7.5.6 and node 14.16.0. I deleted the whole folder and downloaded the repo from scratch.
After `npm install` I get:
```
npm ERR! code E401
npm ERR! Unable to authenticate, your authentication token seems to be invalid.
npm ERR! To correct this please trying logging in again with:
npm ERR!     npm login

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dev\AppData\Local\npm-cache\_logs\2021-03-05T13_39_06_504Z-debug.log
```
The log reports:
```
2196 timing command:install Completed in 45927ms
2197 verbose stack Error: Unable to authenticate, need: Bearer authorization_uri=https://login.windows.net/f6eaefb4-5211-4a08-9024-532af6bb0628, Basic realm="https://pkgsprodcus1.pkgs.visualstudio.com/", TFS-Federated
2197 verbose stack     at C:\Users\dev\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:113:17
2197 verbose stack     at runMicrotasks (<anonymous>)
2197 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2198 verbose statusCode 401
2199 verbose pkgid tsutils@https://bimpress.pkgs.visualstudio.com/_packaging/bp-npm/npm/registry/tsutils/-/tsutils-2.29.0.tgz
2200 verbose cwd C:\Users\dev\Desktop\modelliGEN\xBim\XbimWebUI
2201 verbose Windows_NT 10.0.19042
2202 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
2203 verbose node v14.16.0
2204 verbose npm  v7.5.6
2205 error code E401
2206 error Unable to authenticate, your authentication token seems to be invalid.
2207 error To correct this please trying logging in again with:
2207 error     npm login
2208 verbose exit 1
```
I was using the repo before node.js rewrite, maybe there's some tricks to install npm and node correctly...

**Comment by martin1cerny** [comment]
Use the `master` branch.

**Comment by johnnyontheweb** [comment]
of course I used master branch!

**Comment by martin1cerny** [comment]
Pull the latest version then.  `master` branch isn't pointing to any private npm repositories.

**Comment by johnnyontheweb** [comment]
I'm up-to-date. Some days ago this error was not present, and I don't think https://pkgsprodcus1.pkgs.visualstudio.com/ is private.
I didn't used npm before, so I don't any private repo.
See also [https://stackoverflow.com/questions/59746514/npm-command-not-sending-authorization-token-in-request-unable-to-authenticate](url)
and [https://stackoverflow.com/questions/55958659/unable-to-authenticate-when-trying-to-connect-to-azure-devops-artifacts-feed-t](url)
I don't know how to solve

**Comment by martin1cerny** [comment]
I removed `npx` from the script. Can you try again?

**Comment by johnnyontheweb** [comment]
I tried again after pulling, same error:
```
npm ERR! code E401
npm ERR! Unable to authenticate, your authentication token seems to be invalid.
npm ERR! To correct this please trying logging in again with:
npm ERR!     npm login
```

**Comment by martin1cerny** [comment]
Your directory contains `.npmrc` file which should not be there.

**Comment by martin1cerny** [comment]
```
git clone https://github.com/xBimTeam/XbimWebUI.git
cd .\XbimWebUI\
npm install
npm run start
```

**Comment by johnnyontheweb** [comment]
No, there is not any ".npmc". I started from scratch, unfortunately same error:
```
C:\Users\dev\Desktop\modelliGEN\xBim\XbimWebUI>npm install
npm ERR! code E401
npm ERR! Unable to authenticate, your authentication token seems to be invalid.
npm ERR! To correct this please trying logging in again with:
npm ERR!     npm login

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dev\AppData\Local\npm-cache\_logs\2021-03-09T14_33_37_965Z-debug.log
```
Please find attached the entire log. Thanks for your effort
[2021-03-09T14_33_37_965Z-debug_.zip](https://github.com/xBimTeam/XbimWebUI/files/6109203/2021-03-09T14_33_37_965Z-debug_.zip)

**Comment by martin1cerny** [comment]
I'm sorry, there were residual references to our private NPM feed in package-lock.json. I just pushed new version to `master` which should be clean. It worked on my machine because I'm authenticated to that repository.

**Comment by johnnyontheweb** [comment]
Thanks, finally working!
